service: products-service

frameworkVersion: "3"

plugins:
  - serverless-auto-swagger
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  profile: myProfile
  environment:
    SQS_QUEUE_URL:
      Ref: catalogProductsQueue
    SNS_TOPIC_ARN:
      Ref: createProductTopic

  iamrolestatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        -Fn::GetAtt: [catalogProductsQueue, Arn]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        -Fn::GetAtt: [createProductTopic, Arn]

functions:
  getProductsList:
    handler: handler.getProductsList
    role: "arn:aws:iam::889281469035:role/DynamoDBFullForLambda"
    events:
      - http:
          path: /products
          method: get
          cors: true

  getProductById:
    handler: handler.getProductById
    role: "arn:aws:iam::889281469035:role/DynamoDBFullForLambda"
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true

  createProduct:
    handler: handler.createProduct
    role: "arn:aws:iam::889281469035:role/DynamoDBFullForLambda"
    events:
      - http:
          path: /products
          method: post
          cors: true

  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    role: "arn:aws:iam::889281469035:role/catalogBatchProcessRole"
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogProductsQueue
              - Arn

resources:
  Resources:
    catalogProductsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: catalogProductsQueue
    createProductTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: createProductTopic
    emailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: serhii_yudin@epam.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic

custom:
  autoswagger:
    title: "Products API"
    apiType: "http"
    generateSwaggerOnDeploy: true
    typefiles: []
    swaggerFiles: []
    swaggerPath: "swagger"
    apiKeyHeaders: []
    useStage: false
    schemes: []
    excludeStages: []
    useRedirectUI: false
