service: authorization-service

frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  profile: myProfile

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
